### ISSUE TITLE
Make gridDensity() more generic?

### ISSUE THREAD

**Issue by imckstewart** [lime-rt/lime#155]
I'm bringing my treegrid PR (#93) up to date. This is set up to call `gridDensity()`. I have tried to design the new treegrid functions in as generic and stand-alone manner as possible. This for two reasons: (i) I can think of other applications for this algorithm, (ii) it makes it easier to test and debug improvements to the algorithm. A bit of a flaw in this generic scheme however is the parameter interface of `gridDensity()` in which the number of spatial dimensions is presently hard-wired at 3. The time to fix this is probably now because it is better to introduce `gridDensity()` in the final form we want it in than to introduce in in 1.6 then change the interface later. Thus I propose that we replace `x,y,z` by `x[]`, and pass in `DIM` as a new element of `configInfo`. I think it would also be better practice to return `fracDensity` as the value of the function rather than as a value pointed to by a function argument.

**Comment by tlunttil** [comment]
I've wondered why almost everything in LIME  is passed via pointer arguments instead of just regular returns. I would say that the default should be to `return` and use returning values through pointer arguments only if there's a good reason.

In the other direction, there are some cases (at least various sourceFunc* variants) where a small, often used function has as an argument a struct that in some cases is not that small. Because C calls by value, the structure ends up getting copied and then passed to the function, which in some cases can make call overhead substantial. Inlining sourceFunc_line and _cont gave a 10 to 15% speedup to total runtime in the example model due to eliminating call overhead. If inlining is not possible/desired, it would be better to pass along pointers to structs to eliminate copying large structures.

**Comment by allegroLeiden** [comment]
> It would be better to pass along pointers to structs to eliminate copying large structures.

Excellent idea, thanks.

**Comment by allegroLeiden** [comment]
Fixed by #156
