### ISSUE TITLE
Put the velocity field in the grid structure?

### ISSUE THREAD

**Issue by smaret** [lime-rt/lime#2]
The model density, temperature and abundance are stored in the grid structure. Therefore, the corresponding functions, `density()`, `temperature()` and `abundances()` are called only during the grid construction. On the other hand, the velocity field is not stored into the grid structure, and the `velocity()` function is called many time during the population calculation in the `photon()` function.

Is it possible, from the numerical point of view, to store the velocity field into the grid structure? This would mean that the velocity field have discrete values on the grid point, rather than "smooth", continuous ones. This would have several advantages:

1 - Reduce the number of calls to `velocity()` dramatically, and  decrease the code execution time. This particularly important if we decide at some point to build models from Python. At the moment there are just too many call to the `velocity()` function for this to work without a significant performance cost

2 - Separate the grid construction from the radiative transfert part. If all is stored in the grid, one could create a .vtk file from e.g. Python, and then run the model using the values in this grid.

@christianbrinch: what do you think?

**Comment by imckstewart** [comment]
1.5 years later... there is presently a .vel attribute of the grid struct. The call to velocity() in photon() is unnecessary and I am as we speak replacing it with a read of g[id].vel. There are still calls to velocity() within traceray(), and getting rid of them could be difficult without significant sacrifice of image fidelity. Obviously however doing so is a worthwhile goal, because the user could then (in theory at least) run Lime with a previously constructed grid and without needing to specify the functions at all.
