### ISSUE TITLE
New grid algorithm

### ISSUE THREAD

**Issue by christianbrinch** [lime-rt/lime#205]
I have been playing around the the new versions of LIME (>1.5). I need to weigh my grid point distribution with temperature and density gradients rather than density. How does this work with the new grid point distribution algorithm?

**Comment by allegroLeiden** [comment]
I'm on holiday at the moment and considerably jet lagged still, so I won't comment much on Lime til after I get back on 5 Jan. Briefly however: with Lime-1.7 you choose par->samplingAlgorithm=1 (par->sampling is inactive for this choice), then include a gridDensity() function in the model file which implements the desired recipe. The new algorithm is supposed to produce points which conform exactly to the specified function up to a scalar multiple, the latter because the total number of points is still set from par->pIntensity, thus the number densities one obtains will not be the number densities specified by the gridDensity function, but the latter multiplied by par->pIntensity/(integral over the volume of gridDensity), if that makes sense. Hope this helps.

**Comment by christianbrinch** [comment]
So it is no longer possible to grid according to temperature or a combination of temperature and density?

**Comment by allegroLeiden** [comment]
No, it is still possible, you can call any Lime function from any other. E.g. something like

```
  temperature(r[0],r[1],r[2],temps);
  fracDensity = someFunc(temps[0]);
```
should be perfectly ok within gridDensity.

**Comment by christianbrinch** [comment]
Ok, great!
