### ISSUE TITLE
Seg fault if image is larger than model

### ISSUE THREAD

**Issue by richteague** [lime-rt/lime#212]
If you try to image your model where the projected diameter is larger than your model, that is if

2 * par->radius < pxls * imgres * distance

then you get a segmentation fault at the end of the ray tracing. For example, if you increase the image resolution to 0.5 in the example model, you'll get this fault.

**Comment by tlunttil** [comment]
@allegroLeiden:

It's caused by free on line 1118 of raytrace.c (free on the next line may also cause problems). It may happen that a call to `followRayThroughCells` returns with status 2 without `malloc`ing anything, but also not `NULL`ing the pointers, which then results in double free. I think the cleanest fix would be to change in raythrucells.c
around line 637:  
```
  if(numEntryFaces<=0)
    return 2;
```
to
```
  if(numEntryFaces<=0){
    *chainOfCellIds=NULL;
    *cellExitIntcpts=NULL;
    return 2;
  }
```

**Comment by allegroLeiden** [comment]
Yep. I'd partially fixed this in #209 but even there I had not noticed the return 2. I'll patch it asap.

**Comment by allegroLeiden** [comment]
Actually the problem is more that chainOfCellIds and cellExitIntcpts are not set to NULL after they are freed in raytrace.c. I have fixed code, I'll upload and PR soon.

**Comment by tlunttil** [comment]
Looks fine to me.
