### ISSUE TITLE
Can't write with par->gridOutFiles[i]

### ISSUE THREAD

**Issue by richteague** [lime-rt/lime#231]
When I try and export the grids with `par->gridOutFiles[i]` I encounter the error `Keyword 0 dataype 82 is not currently accepted.`. The models run through properly and the output is as expected so I think this is just an issue with the writing of the grids. It happens for gridding at all stages.

**Comment by tlunttil** [comment]
@allegroLeiden : There seems to be a conflict between datatypes defined in gridio.h and fits datatypes (from fitsio.h); datatype 82 is fits TDOUBLE while gridio.h uses datatype 3 for lime_DOUBLE. I'm going to leave this one to you, since you know what the original intention was.

The typo in error message could also be fixed...

**Comment by allegroLeiden** [comment]
Yeah I actually have this fixed in a branch which I will merge after your PR. I guess I ought to see if 1.7.3 has the same problem and patch that separately.

**Comment by allegroLeiden** [comment]
Ok 1.7.3 does not have this problem so there is no need for a patch. As soon as I can merge the fixed code into the master branch it will go away from there as well. No action until then.

**Comment by allegroLeiden** [comment]
PR #233 has closed this in master branch.
