### ISSUE TITLE
run pylime in imaging-only mode

### ISSUE THREAD

**Issue by yaolun** [lime-rt/lime#264]
I run `pylime` in a two-stages mode, where the first run only calculates the grids and populations and the second run only does raytracing.  I was looking for an option to test out problems during the imaging without running the iterations for solving the populations every time.  

Suggested by the documentation, I use `gridOutFiles` to store the grids during the first run, and use `gridInFiles` to read those grids in the second run.  More parameters for each run are listed below.  However, the second run also solves the populations iteratively, which I do not expect.  I am wondering if there is any other option needed to be set for running `pylime` in this two-stages mode, or it still relies on using `binoutputfile` and `restart`.  Thanks.

> first run:
        par.doSolveRTE = True
        par.gridOutFiles = ['grid1', 'grid2', 'grid3', 'grid4', 'grid5']
        (no imaging parameter is set)

> second run:
par.gridInFiles = ['grid1', 'grid2', 'grid3', 'grid4', 'grid5']
par.img.append(ImageParameters())
(and more imaging parameters)

**Comment by allegroLeiden** [comment]
Sorry this is so complicated - I would love to re-write Lime with a simpler interface, but this would break backward compatibility. I also no longer have time for such a major change, since I am at the end of my contract at Leiden and must soon move to another job.

You can write to multiple grid files, but you can only read one. There is no `gridInFiles` parameter in Lime, just a `gridInFile` parameter which takes a single string argument. If you include such a statement as
```
par.gridInFiles = ['grid1', 'grid2', 'grid3', 'grid4', 'grid5']
```
in your `input()` function, then this will add `gridInFiles` as a new attribute to the `par` instance, but Lime will never read it, since it is not a member of the set of recognized attributes. (Actually I should add a test in Lime to detect such non-official attributes. I'll do that soon and release it as a patch.)

**Comment by yaolun** [comment]
Thanks for quick reply.  You are right.  I misread the parameter name.

Just to clarify the usage of `gridInFile`.  Will LIME automatically starts from different stages based on the kind of input into `gridInFile`?  For instance, if I supply `grid3`, LIME would skip the initial gridding.  If I supply `grid5`, LIME will skip the entire RTE calculation.

**Comment by allegroLeiden** [comment]
Yes, that's the idea. The grid file is designed to contain enough information for Lime to figure out what has been done and not done, and to start from the appropriate stage. If you run the task the first time with `par.gridOutFiles[4] = <my file name>` and `par.nSolveIters` set to some reasonable value, Lime will write the file after iterative solution but before ray tracing; then in your second run if you set `par.gridInFile = <my file name>` and leave `par.nSolveIters` unset (i.e. at default), Lime will not do any more solve iterations, but will simply raytrace the data it finds in the file. That's the idea, anyway.
