### ISSUE TITLE
Possible velocity inversion

### ISSUE THREAD

**Issue by allegroLeiden** [lime-rt/lime#38]
Anika Schmiedeke (Uni Koeln) noted on about 20 Jan 2015:

I'm using LIME version 1.4beta (including the bugfix Christian implemented in 
the getjbar() function in the photon.c file in March 2014).

I initially only modeled SgrB2-M, so the peak of the lines were at 60 km/s. I 
then introduced SgrB2-N to the same model and expected the line peak towards 
SgrB2-N at ~64 km/s. But instead it was at ~56 km/s.

This confused me and I performed a lot of tests with the velocity. Since I'm 
using the predefgrid routine I simply set the gas velocities 

v_x = 0.0 km/s
v_y = 0.0 km/s
v_z = 50.0 km/s

everywhere. When using a source velocity of 60 km/s, the peak of the line was 
located at 70 km/s. When changing v_z to 70 km/s, the line peak was at 50 
km/s. This mirroring behaviour was consistent for all other velocities I 
tested. 

In the LIME paper, it is written, that LIME internally tracks photons by their 
frequency and not relative velocity (Section 2, at the end of page 2). Please 
correct me, if I'm wrong, but I figured, that the 
img[im].pixel[ipx].intense[ichan] array is ordered such that we have the 
frequency axis from left to right. 

So as a test, I've changed the output of the spectral axis to frequency:

	cdelt3  = img[im].velres * restfreq / CLIGHT;
	crpix3  = (double) img[im].nchan / 2. + 1;
	crval3  = restfreq * (1 - img[im].source_vel / CLIGHT);

	fits_write_key(fptr, TSTRING, "CTYPE3  ", &"FREQ    ",    "", &status);  
	fits_write_key(fptr, TDOUBLE, "CDELT3  ", &cdelt3,        "", &status);
	fits_write_key(fptr, TDOUBLE, "CRPIX3  ", &crpix3,        "", &status);
	fits_write_key(fptr, TDOUBLE, "CRVAL3  ", &crval3,        "", &status);
	fits_write_key(fptr, TSTRING, "CUNIT3  ", &"Hz      ",    "", &status);

Using Miriad to perform the switching to velocity (velsw task), everything was 
correct. The line peak for a gas velocity of 70 km/s was at 70 km/s etc. 

Instead of switching the output of the spectral axis to frequency, one could 
also just introduce a minus in the cdelt3 variable, which would invert the 
velocity axis and return the same result.

However, this of course then means, that the spectra are inverted, which is 
very important for asymmetric lines (blue-shifted lines are now actually red-
shifted etc).

**Comment by imckstewart** [comment]
I've looked into this, and I think I understand it. I am undecided however whether to categorize it as poor documentation of the coordinate axes, or as a bug which should be fixed in the code. I'd appreciate comment.

In traceray(), the vector dx points toward the observer; however, since velocity offsets from line centre are essentially set to the dot product of dx and the local model velocity, this means that a model velocity which has a positive-valued radial component will be interpreted as pointing towards the observer, i.e., opposite to the usual astronomical convention, and opposite in sense to the source_vel attribute of the image structure.

To illustrate, suppose we set source_vel=1e3 m/s and theta=0. The latter means that dx=[0,0,-1]. We further specify a uniform model velocity of [0,0,-3e3] m/s, and we suppose that we are making an image of the transition of interest, which means the value of 'shift' in traceray() will be zero. At what velocity will we see line centre? This will occur when deltav-veloproject(dx,g[posn].vel)=0, where deltav=vThisChan - img[im].source_vel + shift. Here veloproject() just performs a dot product. Setting source_vel=1e3 and shift=0 and solving for vThisChan gives us 4e3 m/s. To get 4 with vel=3 rather than -3 we would need to dot by -dx rather than by dx. However the same effect can be obtained simply by making it clear that positive values of the model velocity Z coord point toward the observer, not away.

I favour changing the code myself, but some commentary would be welcome.

**Comment by smaret** [comment]
Should I close this or wait for a definitive fix?

**Comment by allegroLeiden** [comment]
Close it, if you're happy with the convention that receding velocities should be positive, and the result that all cubes will now be flipped in velocity axis. (Before they were wrong, now they are right; but any kind of change is always unpleasant.) The code fix is 'definitive' as such; the only question was whether leaving the code and adjusting instead the documentation would be a better way to address the issue.

**Comment by smaret** [comment]
OK, closing it then.
