### ISSUE TITLE
Provide the H2 total density as an additional parameter

### ISSUE THREAD

**Issue by smaret** [lime-rt/lime#91]
LIME assumes that the total H2 density is that of the first collider. This is a problem if there are several colliders in the file (e.g. p-H2, o-H2 and e-), as pointed out in issues #86 and #58.

One way to solve this issue would be to provide the H2 total density as an additional parameter/function of the `model.c` file. We would then use this density to compute both the gas (e.g. CO) and dust densities. The collider densities would only be used for the excitation.

@christianbrinch, @imckstewart, @ParfenovS and @attilajuhasz : what do you think?

**Comment by attilajuhasz** [comment]
Hi Sebastien, 
Not sure that would be the best way to go as there are situation where H2 does not necessarily play any role, e.g. gaseous debris disks H2 might not even present. I'll think about it and get back if I come up with any better idea. 
Cheers, Attila

**Comment by allegroLeiden** [comment]
I am also concerned with the more software-engineering aspects of the issue. We all know it is sometimes unavoidable (or at least, convenient) to have the same piece of information stored in more than 1 place in code, but of course there should be a single 'master' location which can be pinged at appropriate places to make sure the other storage locations have the same value. The number of 'collision partners' is one of several examples in lime where the inheritance needs to be made more explicit.

**Comment by attilajuhasz** [comment]
I know that in many cases it is convenient to define the abundance with respect to e.g. H2 but if H2 not present or there are more than one collisional partners the definition of the abundance is not that straightforward. My understanding is that the root of the problem is how abundance is converted into molecular density. Is it really out of the question to get rid of the abundance and replace it with molecular density? In the end it is the molecular density and not the abundance that counts in both the excitation calculation and in the raytracing. The abundance is just a "convenience parameter" for the input. If it would solve part of the problem.

**Comment by allegroLeiden** [comment]
Hmm, I don't know. Wouldn't be better to (i) define total density PLUS (ii) abun of everything, radiative and non-radiative? I.e bundle everything together as molecular species but flag those we want to solve the RTE for. Because I imagine the density is going to vary in general much more strongly than the abundances.

**Comment by attilajuhasz** [comment]
Indeed density varies much more than abundance, but internally the abundance is converted to molecular density so it does not matter anyway. The abundance is only used because it seems to be easier to define as the molecular density directly. I.e. one can just simply return 10^-4 for the CO abundance which looks the simplest thing one can do. However, if I don't have H2 in the disk and the main collisional partner is electron then I'm in trouble. If we replaced the abundance with molecular density this trouble shouldn't even come up and a 10^4 CO abundance can be defined just as simple, it requires only one more step : one need to call the density function multiply the result by the desired abundance then return that value. Then if the user insists on using the abundance then in the molecular density function it would be up to him/her to define the abundance the way he/she likes in case of multiple collisional partners. In my opinion this would be more flexible than fixing the abundance definition internally to something that works well in some cases but doesn't in others.

**Comment by allegroLeiden** [comment]
I think we should leave this to the telecon.

**Comment by smaret** [comment]
Fixed with #128.
